### ISSUE TITLE
blockOut and debug option not being applied

### ISSUE THREAD

**Issue by D4NH** [koola/pix-diff#10]
`expect(browser.pixdiff.checkScreen(name, { debug: true, blockOut: { x: 0, y: 0, width: 1080, height: 60 }} )).toMatchScreen();
`

object params are being pushed into the optionsB variable, but do not reflect (can't see the blockOut) on the diff image. any idea what could be wrong? 

im trying to ignore the android status bar, where the clock is.

**Comment by koola** [comment]
It is being ignored according to the diff as it would be highlighted in red otherwise. If you wish to clearly see the visual area being ignored, try set `blockOutOpacity: 0` in the object props.

**Comment by D4NH** [comment]
This is what happens now, it marks the changes in red. But still not blocking the area out which I have given.

{ debug: true, blockOut: { x: 0, y: 0, width: 1080, height: 60 }}

![homepage-pm_samsung_s6](https://cloud.githubusercontent.com/assets/6664547/14277286/dc117f9c-fb22-11e5-8cc5-9847a15612a7.png)

**Comment by D4NH** [comment]
blinkdiff expects and _blockOut:object, but pixDiff passes an array through options. 

when using the following parameter in the expect:

`expect(browser.pixdiff.checkScreen(name, { debug: true, blockOut: [{ x: 0, y: 0, width: 1080, height: 60 }]} )).toMatchScreen(); `

it works correctly and the blockOut is being shown on the diff image
