### ISSUE TITLE
Cannot read property 'browserName' of undefined

### ISSUE THREAD

**Issue by Divyata-Singh** [koola/pix-diff#11]
It gives the above error in index.js file when I do a saveScreen or saveRegion or CheckScreen.
Please find attached my conf file.  I'm trying to take a screenshot of the google homepage in my spec file.Also my protractor version is 3.2.1.
Is there any basic configuration setting that i am missing?

Thanks
Divyata
[protractorConf.txt](https://github.com/koola/pix-diff/files/204284/protractorConf.txt)

**Comment by koola** [comment]
Probably the `.getCapabilities` call is failing and not setting the capabilities object that `browserName' is accessed via. Try setting the screen size to a lower resolution and see if it works.

**Comment by msviha** [comment]
Facing same issue, the getCapabilities() now doesn't work at all (without using pix-diff). I just changed init phase of index.js to use getProcessedConfig()

```
// init
    browser.driver.manage().window().setSize(this._width, this._height)
        .then(function() {
            return browser.getProcessedConfig()
        })
        .then(function(data) {
            return this._capabilities = data.capabilities;
        }.bind(this));
```

**Comment by msviha** [comment]
to getCapabilities now:
```
browser.getCapabilities().then(function(capabilities) {
    console.log(capabilities.get('browserName'))
});
```

previous way doesn´t work
```
browser.getCapabilities().then(function(capabilities) {
    console.log(capabilities.caps_.browserName)
});
```

**Comment by Divyata-Singh** [comment]
With the latest Protractor version it doesn't work but works with Protractor 3.1.1. As @msviha pointed the getProcessedConfig() can be used for getting the capabilities.

**Comment by koola** [comment]
Thanks @msviha, I'll look to adding `capabilities.get('browserName')` compatibility to the next release.
