### ISSUE TITLE
Use with Mocha/Chai

### ISSUE THREAD

**Issue by Legiew** [koola/pix-diff#12]
Hey,

you have a very great module here. We worked out to get it running with our test infrastructure, but only with some quirks cause we are using mocha and chai. Would it be possible to add an option to the module, which test library to use? I had a look at your code and you are just adding matchers to the jasmine object.

My current solution hacked in 5 min to get things working is the following:
```javascript
chai.Assertion.addMethod('matchScreen', function () {
    var result = this._obj;
    var that = this;

    result.then(function (pic) {
        console.log(pic);

        var percent = +((pic.differences / pic.dimension) * 100).toFixed(2);
        console.log(percent);

        that.assert(
            (pic.code === 7) || (pic.code === 5)
            , util.format("Image is visibly different by %s pixels, %s %", pic.differences, percent)
        );
    });
});
```

**Comment by koola** [comment]
Thanks for looking into this. I'll look to adding it into the next release.

**Comment by koola** [comment]
Added in latest release, closing.
