### ISSUE TITLE
PixDiff not resolving path to framework during initialisation

### ISSUE THREAD

**Issue by akkinitsch** [koola/pix-diff#14]
Hi everyone,

I would like to give pix-diff a shot and got the following behaviour:

Part of my protractor.config.js:

`onPrepare: function () {  //configure junit xml report

        var pixDiff = require('pix-diff');
        browser.pixdiff = new pixDiff(
            {
                basePath: 'screenshots/test/',
                width: 1280,
                height: 1024
            }
        );`

I got the following output:

`Error: Cannot find module 'D:\SWE\Nitsch\Entwicklung\Hauptprojekt\Entwicklungszweig\Client\EnMS.Angular\EnMS\Frontendtests\framework\jasmine'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\SWE\Nitsch\Entwicklung\Hauptprojekt\Entwicklungszweig\Client\EnMS.Angular\EnMS\Frontendtests\node_modules\pix-diff\index.js:50:13)
    at Promise.invokeCallback_ (C:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    at C:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
[launcher] Process exited with error code 1
`

It seems that pix-diff cannot resolve the path to the testing framework.

Any suggestions how to handle that problem?

Thank you very much in advance

Akki

**Comment by koola** [comment]
Hi Akki,

Couple questions;

1. What version of protractor are you using?
2. What framework is protractor using?

**Comment by akkinitsch** [comment]
Hi Koola,

i'm using protractor version 3.2.2 with jasmine2 as framework.

Regards

Akki

**Comment by koola** [comment]
I'm suspecting that it's not got the absolute path to the current directory.

Please try the folowing:

1. In Protractor config, make sure ```browser.framework: jasmine2``` is set
2. Inside [index.js on line 50](https://github.com/koola/pix-diff/blob/master/index.js#L50), replace with ```require(path.resolve(__dirname, 'framework', data.framework));```.

**Comment by akkinitsch** [comment]
That solved the problem - thank you very much.

**Comment by koola** [comment]
Thanks for confirming. I'll push the fix in the next release.

**Comment by qualityshepherd** [comment]
This fixed the issue for me as well... thanks! Also, you're missing a comma in index.js on line 44 :)

**Comment by qualityshepherd** [comment]
At the risk of sounding ungrateful for pix-diff, an update will allow me to stop manually fixing this on every `npm install` ;)

**Comment by koola** [comment]
This is fixed and release on v1.0.10

**Comment by qualityshepherd** [comment]
Awesome. Thanks a bunch!
