### ISSUE TITLE
Using "custom" framework with protractor cucumber 

### ISSUE THREAD

**Issue by skorrap** [koola/pix-diff#18]
**config file contains like this:**
framework: 'custom',
frameworkPath: require.resolve('protractor-cucumber-framework'),

When i tried run after installing pix-diff, giving below error:
_E/launcher - Error: Cannot find module 'C:\***\node_modules\pix-diff\framework\custom'_

This actually not an issue as im using different framework other than Jasmine, Jasmine2 or Mocha. Would be great if it can be run through any other framworks. In my case using "protractor-cucumber-framework"

**Comment by koola** [comment]
@skorrap I can look to add support for more frameworks in a future release, but priority is low for now.

**Comment by wswebcreation** [comment]
Hi @koola,

I already made a fork to add support and add unit tests with cucumber. I can make a PR for it if you want.

I also got some extra "features"/"fixes", also interested?

**Comment by skorrap** [comment]
@koola @wswebcreation-Thanks for response..
@wswebcreation -  looks very close to my requirement. Have one question though about matchers
with custom framework -  can we use .toMatchScreen(); or .matchScreen();? - It saying those are not a functions.

**Comment by wswebcreation** [comment]
@skorrap

There are no matchers for Cucumber.js, also mentioned it in the readme with an example because Cucumber.js doesn't have an own 'expect' method, you need 'chai' and 'chai-as-promised' and create an own method

**Comment by koola** [comment]
@wswebcreation Thanks a lot for the PR! Already merged in master so closing this issue.

**Comment by wswebcreation** [comment]
Your are welcome!
