### ISSUE TITLE
Requesting name change for 'toMatch' matcher.

### ISSUE THREAD

**Issue by nsnagarajan** [koola/pix-diff#2]
Hi,
I am working with pix-diff. Got to know that [pix-diff implemented a toMatch()](https://github.com/koola/pix-diff/blob/master/index.js#L211) matcher that conflicts with Jasmine's default toMatch() matcher. It would be helpful if you rename that matcher to something more specific like toMatchScreenshot, or I can change that and can create a PR for that.

Thanks,
Nagarajan NS

**Comment by koola** [comment]
Thanks for pointing this out. Fixed in commit df527a6

**Comment by nsnagarajan** [comment]
Thanks for the immediate action!
