### ISSUE TITLE
DevicePixelRatio Fix broken for Firefox and save/checkRegion not correct after scroll

### ISSUE THREAD

**Issue by wswebcreation** [koola/pix-diff#20]
**Used version:** 1.0.11
**Tested on browsers:** Chrome / Firefox / Safari / Internet Explorer 11

**Issues:**

- devicepixelratio fix isn't working for Firefox
- save/checkRegion isn't taking correct screenshots

**Steps _devicepixelratio fix isn't working for Firefox_:**
Take screenshots of an element in Firefox with `saveRegion`

**Steps _save/checkRegion isn't taking correct screenshots_:**
Take the jasmine unittests, add a testcase to set the height of the browser and scroll to the title, in chrome + safari the screenshot is not correct, in firefox and IE it's correct

**Fix:**
@koola, I created a possible fix for it. Please check if you agree with it so I can create a PR for it
[possible fix](https://github.com/wswebcreation/pix-diff/tree/fix/firefox-support-region-devicepixelratio). This fix is in determining the position of the element based on postion to top of page and top of screen.
Can the Travis also test on Firefox and if so, what do I need to change in the .travis.yml file?

Here are screenshots to show the difference between chrome and firefox webdriver implementation of taking a screenshot of a region and taking a screenshot of a screen.

**Chrome region**
![scrolledpageregion-chrome-800x200](https://cloud.githubusercontent.com/assets/11979740/17944713/256b0e00-6a41-11e6-991a-a17d6f7c813e.png)

**Firefox region**
![scrolledpageregion-firefox-800x200](https://cloud.githubusercontent.com/assets/11979740/17944712/2566fe5a-6a41-11e6-8aca-9b744ff8af4e.png)

**Chrome screen**
![objectobject-chrome-800x200](https://cloud.githubusercontent.com/assets/11979740/17944711/2566127e-6a41-11e6-9f31-234376fb7b9f.png)

**Firefox screen**
![objectobject-firefox-800x200](https://cloud.githubusercontent.com/assets/11979740/17944710/25630782-6a41-11e6-8d30-b08817d1acaa.png)

**Comment by koola** [comment]
Thanks for raising this @wswebcreation and the fix. I've raised a PR for us to discuss more.

**Comment by koola** [comment]
Merged in PR #25

**Comment by wswebcreation** [comment]
Tnx!
