### ISSUE TITLE
generate baseline if one doesn't exist.

### ISSUE THREAD

**Issue by leonardoanalista** [koola/pix-diff#21]
This would be a pretty good feature to have. I use `PhantomCSS` and they provides a good command line feedback for first run.
Would this be possible here?

**Comment by koola** [comment]
@leonardoanalista That's not a bad idea. Currently to take a baseline, you'd insert ```saveScreen``` or ```saveRegion``` to build up your image library, then replace with ```checkScreen``` or ```checkRegion``` for comparisons.

**Comment by wswebcreation** [comment]
Hi @koola,

What we did in the past is that the checkScreen / -Region had a saveScreen / -Region with something like this

```
this.saveScreen(tag);

try {
    fs.accessSync(path.join(baselineFolder, screenFileName), fs.F_OK);
} catch (e) {
    return new Promise(function (resolve, reject) {
        reject(new Error('\n\n ## No baseline image available, saving actual image ## \n'));
    });
    }
```

**Comment by abierbaum** [comment]
I agree that this would be a great addition.

**Comment by PramodDutta** [comment]
+1 ( Waiting for this to happen , currently using PhantomCSS Tests)

**Comment by koola** [comment]
This is in release v1.0.12, enjoy!

**Comment by leonardoanalista** [comment]
awesome! thanks
