### ISSUE TITLE
pass options to underlying image comparison tool 

### ISSUE THREAD

**Issue by leonardoanalista** [koola/pix-diff#22]
I noticed `blink-diff` takes many params. One of them is `--copyImageB`. Woiuld be possible to allow `pix-diff` to pass options over to `blink-diff`?

If not, what I really want is to have, for a given test, 3 versions of the image:
  * first: the baseline image (I have already or pix-diff could create for me for first time) 
  * second: image highlighting the difference (this tool does this via blink-diff)
  * third: the action image result. **This is the missing one**.

It would be great to have the actual image for scenarios where the new actual image needs to be the new baseline. 

Leonardo

**Comment by koola** [comment]
@leonardoanalista You can pass an options object to either `checkScreen` or `checkRegion` as the second parameter. This object is directly passed to Blink-diff after being merged with some defaulted options.

Koola
