### ISSUE TITLE
this.checkImageExists(...).catch is not a function

### ISSUE THREAD

**Issue by scaljeri** [koola/pix-diff#28]
When I run pix-diff I always get the following error:

     Message:
        Failed: this.checkImageExists(...).catch is not a function
      Stack:
        TypeError: this.checkImageExists(...).catch is not a function
        ...

It seems to go wrong here:

        checkScreen: function (tag, options) {
            var defaults;

            return this.flow.execute(function () {
                return this.checkImageExists(tag)
                    .catch(function (err) {  ...  }
             ...

Now the `checkImageExists` returns a promise

     var deferred = protractor.promise.defer();
     ...
     return deferred.promise;

I've checked this promise and it doesn't have a `catch` method

My node version is v6.5.0 and I'm using protractor v4.0.5

For now I've fixed it as follows:

    checkScreen: function (tag, options) {
        var defaults;

        return this.flow.execute(function () {
            return this.checkImageExists(tag)
                .then(function () {
                    return browser.takeScreenshot();
                }, function (err) {
                    if (this.baseline) {
                        this.saveScreen(tag);
                    }
                    else {
                        throw err;
                    }
                }.bind(this))
                .then(function (image) {
                    tag = this.format(this.formatString, tag);
                    defaults = {
                        imageAPath: path.join(this.basePath, tag),
                        imageB: new Buffer(image, 'base64'),
                        imageOutputPath: path.join(this.basePath, 'diff', path.basename(tag)),
                        imageOutputLimit: BlinkDiff.OUTPUT_DIFFERENT
                    };
                    return new BlinkDiff(this.mergeDefaultOptions(defaults, options)).runWithPromise();
                }.bind(this))
                .then(function (result) {
                    return result;
                });
        }.bind(this));
    },

**Comment by koola** [comment]
Thanks for providing your solution @scaljeri, however on my local with Node `v5.10.1` and Protractor `v4.0.5` all test are passing, same on CI;
```
$ node --version
v6.5.0
$ npm --version
3.10.3
$ nvm --version
0.31.6
```
Checking the [Selenium-webdriver promise.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/promise.js#L446), shows the correct way to handle thrown errors, which PixDiff is doing correctly. Suggest you clear your workspace and `npm install` again.

**Comment by koola** [comment]
So this is passing on my local. According to the docs, the error should propagate up the stack, but interesting an implicit return and throw is now required. 

```
    checkScreen: function (tag, options) {
        var defaults;

        return this.flow.execute(function () {
            return this.checkImageExists(tag)
                .then(function () {
                    return browser.takeScreenshot();
                }, function (err) {
                        if (this.baseline) {
                            return this.saveScreen(tag).then(function () {
                                throw err;
                            })
                        }
                        throw err;
                    }.bind(this))
                .then(function (image) {
                    tag = this.format(this.formatString, tag);
                    defaults = {
                        imageAPath: path.join(this.basePath, tag),
                        imageB: new Buffer(image, 'base64'),
                        imageOutputPath: path.join(this.basePath, 'diff', path.basename(tag)),
                        imageOutputLimit: BlinkDiff.OUTPUT_DIFFERENT
                    };
                    return new BlinkDiff(this.mergeDefaultOptions(defaults, options)).runWithPromise();
                }.bind(this))
                .then(function (result) {
                    return result;
                });
        }.bind(this));
    }
```

**Comment by scaljeri** [comment]
I've removed all my dependencies and it works again. I though I did that yesterday too. Anyway, not sure if this is still a valid issue!

**Comment by koola** [comment]
@scaljeri No worries, I've refactored and improved the error handling with commit 370e8e8cfcac7adffa2336c25ee66ed72d5d46fb
