### ISSUE TITLE
Threshold value?

### ISSUE THREAD

**Issue by nsnagarajan** [koola/pix-diff#3]
Is there any option to set threshold in pix-diff?

**Comment by koola** [comment]
There is, see the test spec [here](https://github.com/koola/pix-diff/blob/master/test/integration.spec.js#L31). The default value is 500 pixels.

**Comment by nsnagarajan** [comment]
Thanks a lot!!

**Comment by joao10falcao** [comment]
Is it possible to set it on the declaring the pix-diff globally instead on the matched?

**Comment by koola** [comment]
Not at this time. I'll look to add it in the next release as I agree it would be quite useful.
