### ISSUE TITLE
consider to support multiCapabilities

### ISSUE THREAD

**Issue by josephlaw** [koola/pix-diff#32]
Please consider to support multiCapabilities, thanks

**Comment by wswebcreation** [comment]
@josephlaw ,

Can you explain what the problem and or question is exactly? I'm using PixDiff with multiple browsers and it works fine on my local machine and from Jenkins.

**Comment by josephlaw** [comment]
sorry, i make mistake myself. pix-diff support multiCapabilities. thanks.

**Comment by wswebcreation** [comment]
@josephlaw, no probs

@koola , can you close this issue? Or give me te rights to do it in the future?
