### ISSUE TITLE
checkRegion blockout size incorrect

### ISSUE THREAD

**Issue by josephlaw** [koola/pix-diff#33]
I use jasmine2 as below, the result image can be created but the size cropped (no date at the title bar), any idea? 
`expect(browser.pixDiff.checkRegion($(":root"),'examplePage',{blockOut: [{x: 0, y: 0, width: 412, height: 50}]})).toMatchScreen();`

![android emulator-412x732](https://cloud.githubusercontent.com/assets/8828433/19830038/7c06e33c-9e22-11e6-8014-eb969ddcc8b5.png)

Another successful result image when using below 
`expect(browser.pixDiff.checkScreen('examplePage')).toMatchScreen();
`
![android emulator-412x732](https://cloud.githubusercontent.com/assets/8828433/19830003/bfe17000-9e21-11e6-977f-625877d5e210.png)

**Comment by wswebcreation** [comment]
Yes I think I know why

I'm currently working with @koola on Appium support. The problem in this case it that the emulator also has a devicePixelRatio (depending on the emulator you use) you need to multiply the height and width with the devicePixelRatio for the blockout

So if dpr = 3 then you know what to do.  Hope it helps

Grtz 

Wim

**Comment by josephlaw** [comment]
hi @wswebcreation thank your reply, but i got the same result even multiply the height and width with devicePixelRatio = 3.

I also use Appium

**Comment by josephlaw** [comment]
hi @wswebcreation thanks your reply. Got correct after multiply with devicePixelRatio.

But there is time cropped if image is visibly different.

**Comment by wswebcreation** [comment]
Hi @josephlaw ,

Can you share the screen? Is it an app? By the way, checkRegion won't work correctly on elements that need to be scrolled, that's what @koola and I are working on.

**Comment by josephlaw** [comment]
@wswebcreation, screen already in my first post.
i test hybrid app on Android emulator through appium, and my root element (just full screen) is not allow scrolling. thanks.

**Comment by wswebcreation** [comment]
Hi @josephlaw ,

I don't understand what you mean. Is there still a problem now?
If so, can you explain it more and give an example script with the steps?

**Comment by josephlaw** [comment]
Hi @wswebcreation ,

as captured below showing that the result image missing the date field.
`expect(browser.pixDiff.checkRegion($(":root"),'examplePage',{blockOut: [{x: 0, y: 0, width: 1236, height: 30 }]})).toMatchScreen();`
<img width="1130" alt="screen shot 2016-10-30 at 2 06 51 pm" src="https://cloud.githubusercontent.com/assets/8828433/19834810/7c965944-9eaa-11e6-90dc-ba1ab01243df.png">

but below showing the result image have date field which is correct result. thanks `expect(browser.pixDiff.checkScreen('examplePage')).toMatchScreen();`
<img width="1309" alt="screen shot 2016-10-30 at 2 09 50 pm" src="https://cloud.githubusercontent.com/assets/8828433/19834811/9421f97e-9eaa-11e6-8d40-ce3be3fead08.png">

**Comment by wswebcreation** [comment]
Hi @josephlaw,

Is there still an issue now?

**Comment by josephlaw** [comment]
hi @wswebcreation , can i raise it (enlarge) as another issue?

**Comment by wswebcreation** [comment]
I don't think Enlarge is an issue. 

The checkRegion crops from the original screen the part that is located as `$(":root")`. The dimensions of the `$(":root")` is smaller then the complete screen. 
If you would print the dimensions of `$(":root")` you will see that it will differ from the original size of the screen.

If you want to take the screenshot of the complete screen only use `checkScreen`. As also said, Appium is not officially supported by PixDiff, see https://github.com/wswebcreation/pix-diff/blob/feat/add-appium-support/docs/appium.md my branche docs about Appium and what PixDiff will support in the future.

Hope it's clear now.

**Comment by koola** [comment]
Thanks @josephlaw for raising this issue and @wswebcreation for the quick response!

Will look to adding DPR support for additional parameters passed to Blinkdiff via Pix-diff shortly.
