### ISSUE TITLE
autoResize doesn't work correctly

### ISSUE THREAD

**Issue by Ivan-Katovich** [koola/pix-diff#34]
autoResize Auto (re)size the browser (default: true)
It doesn't work correctly 
The row 42 in index.js "this.autoResize = options.autoResize === false || true;" returns true anyway.
You have to replace it with something like 
"this.autoResize = options.autoResize === false ? false : true;"

**Comment by necramirez** [comment]
Better yet: `this.autoResize = !(options.autoResize === false)`
