### ISSUE TITLE
getBrowserDimensions returns incorrect dimensions

### ISSUE THREAD

**Issue by necramirez** [koola/pix-diff#36]
https://github.com/koola/pix-diff/blob/6ebf6521e7b2d98f336fafc28c3801ec628b3482/index.js#L240-L242

```
    getBrowserDimensions: function () {
        return browser.executeScript('return { height: window.screen.height, width: window.screen.width};');
    },
```

^ returns the _screen's_ dimensions -- so when I'm on a 1920x1200 monitor, that's the dimensions I get, instead of my browser's actual size.

**Comment by wswebcreation** [comment]
Hi @necramirez,

Thnx for the feedback, you are right. I should be more like this

`````
// we need screen.height for the appium implementation, outerHeight for the desktop implementation
const windowHeight = this.platformName? 'window.outerHeight' : 'window.screen.height',
windowWidth = this.platformName ? 'window.outerWidth' : 'window.screen.width';

return browser.driver.executeScript(`return { height: ${windowHeight}, width: ${windowWidth}};`);
`````

@koola can you pick this up also with https://github.com/koola/pix-diff/pull/37

**Comment by koola** [comment]
This is fixed, closing.
