### ISSUE TITLE
If browser returns half pixel for getLocation() saveRegion/checkRegion fails

### ISSUE THREAD

**Issue by nathan-grant** [koola/pix-diff#4]
Hi thanks for your helpful project.  I came across a bug today that is down somewhere at the Sauce/Selenium/Browser level but I think there is an easy way to handle it in this repo, if you so choose :)

Basically I was doing some save/checkRegion code for a login box, and when I run it locally (OSX/Chrome) I get the region cropped with no issues, but when I execute the protractor test on SauceLabs I often get a X/Y position containing half numbers: for example 
rect = { height: 335, width: 402, x: 440, y: 281.5 }
When this rect is passed to PNGImage as cropImage, PNGImage I believe disregards the half number and I get another region of the screen (in my case a blank image).  If I manually Math.floor() those coordinates the crop and comparison works just fine.

I'm thinking a small change something like something like:

     .then(function(point) {
                        rect = {height: size.height, width: size.width, x: Math.floor(point.x), y: Math.floor(point.y)};
                        return browser.takeScreenshot();
                    })

If you think that is an acceptable addition I'm happy to make a PR for you as well.

Thanks

**Comment by koola** [comment]
Apologies for the late reply. Thanks for looking into this and providing the PR, which is merged and publish in [v1.0.7](https://github.com/koola/pix-diff/releases/tag/v1.0.7).
