### ISSUE TITLE
Allow window size to be provided by browser capabilities

### ISSUE THREAD

**Issue by necramirez** [koola/pix-diff#40]
If `autoResize` is set to `false`, I expect the screenshots to use the dimensions specified in Protractor's capabilities config. For example, the following `multiCapabilities` config is not supported by `pix-diff`:
```
    multiCapabilities: [
        {
            browserName: 'chrome',
            chromeOptions: {
                args: ['--lang=en', '--window-size=1440,900']
            }
        },
        {
            browserName: 'chrome',
            chromeOptions: {
                args: ['--lang=en', '--window-size=400,900', '--user-agent=\'Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B137 Safari/601.1\'']
            }
        }
    ],
```

because the browser dimensions are only used when `platformName` is present (as I understand, this is when run through Appium) -- `platformName` is empty on desktop:
https://github.com/koola/pix-diff/blob/6ebf6521e7b2d98f336fafc28c3801ec628b3482/index.js#L79-L82
```
        if (this.platformName) {
            this.height = dimensions.height;
            this.width = dimensions.width;
        }
```

And, right now, `width` and `height` always fall back to 1280x1024, as per:  https://github.com/koola/pix-diff/blob/6ebf6521e7b2d98f336fafc28c3801ec628b3482/index.js#L44-L45
```
    this.width = options.width || 1280;
    this.height = options.height || 1024;
```

so my runs always write the images as if they were 1280x1024, despite the window sizes I provided in the `multiCapabilites` config.

I'm thinking if https://github.com/koola/pix-diff/blob/6ebf6521e7b2d98f336fafc28c3801ec628b3482/index.js#L79-L85 :
```
        if (this.platformName) {
            this.height = dimensions.height;
            this.width = dimensions.width;
        }
        else if (this.autoResize) {
            browser.driver.manage().window().setSize(this.width, this.height);
        }
```

should be rewritten into:

```
        if (this.autoResize) {
            browser.driver.manage().window().setSize(this.width, this.height);
        }
        else {
            // use device/browser dimensions when on Appium or when on desktop where `autoResize == false`
            this.height = dimensions.height;
            this.width = dimensions.width;
        }
```

**Comment by wswebcreation** [comment]
Hi @necramirez ,

Tnx, we'll look into that

**Comment by necramirez** [comment]
Just tested my suggested code change locally, and it works for me. 😁 

I don't use Appium (yet) though, so I'll leave it to you guys to consider (and test). I'll write a PR for this and park it here. 😜

**Comment by wswebcreation** [comment]
tnx

**Comment by koola** [comment]
Thanks @necramirez for the PR, merged.
