### ISSUE TITLE
Documentation request: threshold and other BlinkDiff options

### ISSUE THREAD

**Issue by necramirez** [koola/pix-diff#41]
~~I see that https://github.com/yahoo/blink-diff has `threshold` and `thresholdType` options. Sounds useful to be able to control it.~~

Going through the source code, it seems its possible to pass in BlinkDiff options to a `checkScreen()`/`checkRegion()` call. Would be nice to know that in the documentation. 😁

**Comment by koola** [comment]
Yes, we plan on improving the documentation so that these are clear. Expect more complete docs along with the appium merge.

**Comment by koola** [comment]
Hi @necramirez, have added more documentation so is it clear enough for you now?

**Comment by necramirez** [comment]
👍
