### ISSUE TITLE
incorrect width and heigth in 1.1.16

### ISSUE THREAD

**Issue by josephlaw** [koola/pix-diff#44]
I had set the width and height in protractor configure file (for Linux and Chrome), but the pix-diff haven't get correct size (e.g. it try to find base image xxxx-linux-1008x765.png). so i switch back to use 1.0.14.  Or something else i need to set? thanks.

```
var PixDiff = require('pix-diff');
        browser.pixDiff = new PixDiff(
        {
          basePath: './baseimg/',
          diffPath: './baseimg/diff/',
          width: 412,
          height: 732,
          formatImageName: '{tag}-{deviceName}-{width}x{height}',
        }
      );
```

**Comment by josephlaw** [comment]
Why set isMobile to true if i put value into deviceName?
```
      /**
       * Check if Mobile
       *
       * @method _isMobile
       * @returns {boolean}
       * @private
       */
      _isMobile() {
          return this.deviceName !== '';
      }
```

**Comment by koola** [comment]
Hi @josephlaw, ```deviceName``` is used for Appium mobile testing only. Using ```name``` is the correct usage for your scenario.
