### ISSUE TITLE
Old version of Blink-Diff

### ISSUE THREAD

**Issue by johnvnguyen** [koola/pix-diff#45]
Is it a problem to upgrade the blink-diff dependency version in package.json from 1.0.12 to something higher?

I found this bit in blink-diff's index.js: `this._threshold = options.threshold || 500;`
When I set the threshold to 0, it becomes a problem. 

The newest version of blink-diff checks if it is undefined:

>function load(value, defaultValue) {
return (value == null) ? defaultValue : value;
}
this._threshold = load(options.threshold, 500);

**Comment by koola** [comment]
Hi @johnvnguyen, no problem will bump it soon.

**Comment by koola** [comment]
I've pushed 1.2.0 which included PixelDiff as the new comparison engine. It's effectively a fork of BlinkDiff with patches applied to fix the outstanding issues.

**Comment by johnvnguyen** [comment]
Nice, thanks!
