### ISSUE TITLE
Bug: Canvas regions save filename with wrong screen sizes on Chrome

### ISSUE THREAD

**Issue by qualityshepherd** [koola/pix-diff#49]
On my macbook pro (retina screen), when I run tests using pix-diff, they are saving the files as `...chrome-2048x1554-dpr-2.png`, even though I specify width/height in the pix-diff options as 1024/800, and specify the browser size in my Protractor config to also be 1024/800. This _doesn't_ happen when I run them on Linux.

This doesn't occur when running tests on Firefox, nor when using Pix-diff 1.0.14. Seems like retina is mucking up the dimensions pix-diff is pulling?

**Comment by koola** [comment]
Thanks @qualityshepherd , I'll take a look at this

**Comment by koola** [comment]
From master I can't reproduce the issue. Planning on releasing a new version this week.

**Comment by qualityshepherd** [comment]
Hmmm... then _I'll_ take a look :) Thanks!

**Comment by qualityshepherd** [comment]
Oh, duh... sorry... this occurs with _regions_ when the target is a canvas. Here's a quick test that will reproduce the issue...

Also, if you uncomment the expect, it reproduces #15

```
var PixDiff = require('pix-diff');

describe('Pix-Diff', function() {

    beforeEach(function() {
        browser.pixdiff = new PixDiff({
            basePath: './',
            diffPath: './',
            width: 1024,
            height: 800
        });
    });
    
    it('should get canvas dimensions correctly', function() {
        var tag = 'canvas-test';

        browser.get('http://www.w3schools.com/html/html5_canvas.asp');
        browser.pixdiff.saveRegion($('#myCanvas'), tag);

        //expect(browser.pixdiff.checkRegion($('#myCanvas'), tag)).toMatchScreen();
    });
});
```

**Comment by qualityshepherd** [comment]
@koola are you able to reproduce this with the example test ^^?

**Comment by koola** [comment]
@qualityshepherd I'm not able to reproduce from master, however the matchers are a problem that I'm working on.

**Comment by koola** [comment]
@qualityshepherd after poking around I am able to reproduce and am working on it.

**Comment by qualityshepherd** [comment]
Awesome. This is blocking some tests I want to finish. 

BTW, love pix-diff... thanks a bunch!

**Comment by koola** [comment]
@qualityshepherd latest version is out! Tests are all passing on my local mbp.

**Comment by qualityshepherd** [comment]
This is still an issue with 1.2.1.

**Comment by wswebcreation** [comment]
1.2.2 is out

**Comment by qualityshepherd** [comment]
oh... sorry, yeah, 1.2.2. 

The example is also saving the png at the wrong size. Eg... 

![image](https://cloud.githubusercontent.com/assets/3298906/21896856/5fc2fa24-d8ad-11e6-900c-a9c1df54554a.png)

**Comment by wswebcreation** [comment]
Size is correct, size is of the complete screen. You will find it in the docs

**Comment by qualityshepherd** [comment]
On my actual tests, the screen should be 1024x777, but the saved png is 2048x1554. On Firefox, this is not an issue.

**Comment by wswebcreation** [comment]
Do you have a Mac with a Retina display? If so, then the device pixel ratio is 2, that's why it's twice as big.
Firefox is defaulted to 1 because the screenshot size is not influenced by the DPR

It's up to @koola to fix this / to determine if he sees this as a bug

**Comment by wswebcreation** [comment]
For the naming of the file the docs / code will explain why this happens.

As said, it's up to @koola what to do with it. Based on the current code/docs it don't think it's an issue

**Comment by qualityshepherd** [comment]
Yeah, I understand... I might have to find another solution for visual testing

**Comment by wswebcreation** [comment]
What's the real problem then, do you need to have the screenshot size in your filename?

If not, create a custom filename. See the docs

**Comment by qualityshepherd** [comment]
As per the docs, this issue is fixed, so I'll close it. 

My issue is that I run tests on multiple environments, and this adds to the maintenance pains. These pains are obviously inevitable for visual testing, so this is partially just me being annoyed by having to have _two_ mac baselines for each test (retina and non-retina). My confusion was due to the breaking change update, and being used to the old version. So sorry for that. 

Thanks for the help!

**Comment by wswebcreation** [comment]
The issue is that the screenshots are created based on the dpr on a screen/device. 
You can "fix" this by using an external screen on which you know the dpr is 1 (mostly connected with VGA)

"We" could resize the screenshot to dpr=1 but that could result in resizing issues during comparisons

**Comment by qualityshepherd** [comment]
It's a hard problem. The argument for this still being a "bug" is that it's inconsistent accross browsers... but lots for things are. If you can "fake" the dpr to 1, and not have differences, that'd be great. Doesn't seem like that would work though, just like resize wouldn't work. Ain't nothing easy :)

We run tests locally on macs, some of which have retinas. I also run them headlessly on ubuntu/xvfb, which also needs its own baseline. CI will likely require _its_ own baseline, etc.... Sadness. 

Obviously, the fewer baseline images you need to maintain the better... so that's the frustration with this.

**Comment by wswebcreation** [comment]
I think you got the core of the problem

Each browser has its own image and even an image on chrome windows can differ from chrome on mac / ubuntu.

That is what makes image comparison so hard /difficult (or you need paid solutions like Applitools)

You can work with blinkdiff options to minimize the differences, but then you will get false positives or a higher change on that

**Comment by qualityshepherd** [comment]
Agreed.
