### ISSUE TITLE
Cannot overwrite default options

### ISSUE THREAD

**Issue by jvornkahl2222** [koola/pix-diff#54]
We cannot overwrite the default options. We want to save a diff image if there is a similar output. 

Line 178 in index.js _mergeDefaultOptions handle custom options.

We think this code is better:
`if (optionsB.hasOwnProperty(value)) {
                optionsA[value] = optionsB[value];
            }`

**Comment by jvornkahl2222** [comment]
Thank you for your support.

Do you update version 2.0.0? What is the best and fastest way to fix it for everyone?

**Comment by koola** [comment]
Hi @jvornkahl2222, the patch committed fixes your issue. However the build is failing for other reasons so when I have some free time to make the build green, I'll push a minor release.

In the meantime, you can update your `package.json` to point at this commit.

**Comment by koola** [comment]
Released in 2.0.1
