### ISSUE TITLE
Incorrect base image name when call save region with given formatImageName

### ISSUE THREAD

**Issue by chinhnguyen8855** [koola/pix-diff#55]
OS: Mac (Sierra)
pix-diff version : 2.0.1
framework: cucumberjs
browser: Chrome

I tried to save a region base image with given formatImageName but it does not work.
Could you please help?

Here is snippet...

var PixDiff = require('pix-diff');
var pageMapRegion = 'pageMap';

browser.pixDiff = new PixDiff({
    basePath: './screenshots/',
    diffPath: './screenshots/',
    width: 1800,
    height: 1100,
    formatImageName: '{tag}-{browserName}'
});

    this.When(/^I save the page map region of the page$/, function () {
        return browser.pixDiff.saveRegion(element(by.id('np-p-page-map-container-id'), pageMapRegion));
    });

And here is result:
![image](https://user-images.githubusercontent.com/3290297/28193598-defd7880-67f2-11e7-922e-cc14392b6b1e.png)

**Comment by koola** [comment]
Hi @chinhnguyen8855 
Looks like  `var pageMapRegion` is scoped, but you're trying to use it globally.

Either make it global ```global pageMapRegion = 'pageMap';``` or define it in your step:

```javascript
this.When(/^I save the page map region of the page$/, function () {
    var pageMapRegion = 'pageMap';
    return browser.pixDiff.saveRegion(element(by.id('np-p-page-map-container-id'), pageMapRegion));
});
```

**Comment by chinhnguyen8855** [comment]
Hi koola,
I removed variable, and passed as a string but it is still same result.  Am I missing something?

   this.When(/^I save the page map region of the page$/, function () {
        return browser.pixDiff.saveRegion(element(by.id('np-p-page-map-container-id'), 'pageMap'));
    });

Result:
![image](https://user-images.githubusercontent.com/3290297/28200165-44055bf4-681f-11e7-8037-45e73604b734.png)

**Comment by koola** [comment]
You're including `pageMap` in element, not `saveRegion` in the original snippet.

Try:

this.When(/^I save the page map region of the page$/, function () {
    var pageMapRegion = 'pageMap';
    return browser.pixDiff.saveRegion(element(by.id('np-p-page-map-container-id')), pageMapRegion);
});

**Comment by chinhnguyen8855** [comment]
Thanks koola!... It works now.
