### ISSUE TITLE
Error: ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by mfulton26** [koola/pix-diff#56]
I'm trying to try out pix-diff but I cannot get it to run:

```js
  onPrepare: () => {
    console.log(browser.constructor.name);
    const PixDiff = require('pix-diff');
    browser.pixDiff = new PixDiff(
      {
        basePath: 'path/to/baseline/',
        diffPath: 'path/to/diff/',
        width: 1366,
        height: 768
      }
    );
```

```
ProtractorBrowser
[15:47:57] E/launcher - Error: ReferenceError: browser is not defined
    at new PixDiff (\node_modules\pix-diff\index.js:72:13)
    at onPrepare (\conf.ts:26:23)
```

`browser` is clearly defined but for some reason PixDiff cannot find it.

**Comment by koola** [comment]
Can you try the following:

```javascript
  onPrepare: () => {
    const PixDiff = require('pix-diff');
    browser.pixDiff = new PixDiff(
      {
        basePath: 'path/to/baseline/',
        diffPath: 'path/to/diff/'
      }
    );
    browser.driver.manage().window().setSize(1366, 768);
```

Also make sure option ```noGlobals``` is not set to true in [config.ts](https://github.com/angular/protractor/blob/42846ec5eb12ae58c4105a7e21030d1be87032c7/lib/config.ts#L196)

**Comment by mfulton26** [comment]
Oh, that makes a lot of sense, I actually do have `noGlobals` set. Hmmmm, is there any way to use pix-diff with `noGlobals: true`?

**Comment by koola** [comment]
Not really I'm afraid atm. I'll add check in a future release to make this more obvious and verbose.
