### ISSUE TITLE
Inconsistence test result when call checkRegion api

### ISSUE THREAD

**Issue by chinhnguyen8855** [koola/pix-diff#57]
OS: Mac (Sierra)
pix-diff version : 2.0.1
framework: cucumberjs
browser: Chrome

Hi,
I use checkRegion to compare the given base region screenshot against in test region image.  I tested on same client (Mac/Chrome).  However, the test result is very inconsistence.  Sometimes it passed, other times it failed.
Could you please help with some suggestions?

Here is utility js file:

   /**
     * @description Compare a full screen or a region of a screen
     * @param element - element to identify region of screen to save or to compare
     * @param area - area of the screen, use full or region
     * @param tagName - tag name of a saving image.  This is required format of pix-diff tool.
     * see https://github.com/koola/pix-diff/blob/master/docs/conventions.md for more details
     * @param waitTimeout - wait timeout
     * @param errMessage - error message
     * @returns {Promise}
     */
    compareFullScreenOrRegion: function (element, area, tagName, waitTimeout = 30000, errMessage = 'Element is not visible, or not able to retrieve.') {
        if (!(element) || !(tagName) || !(area)) {
            throw new Error('Element or tag name or area is not defined.');
        }
        return helper.waitVisibility(element, waitTimeout, errMessage)
            .then(() => {
                switch (area.toLowerCase()) {
                    case 'full':
                        return browser.pixDiff.checkScreen(tagName);
                    case 'region':
                        return browser.pixDiff.checkRegion(element, tagName);
                    default:
                        throw new Error('Screen area ' + area + ' is not supported.  Use full or region');
                }
            });
    }

Here is in step file:

   /**
     * This step will compare a region or a full screen image of page map with a given tag name
     * Pass "region" if wanted to compare a region of a screen
     * Pass "full" if wanted to compare a whole screen
     * For tag name use camel case
     */
    this.Then(/^"([^"]*)" screenshot of page map page with tag name "([^"]*)" is matched$/, function (area, tagName) {
        return pixDiffUtil.compareFullScreenOrRegion(pageMapView.pageMapPage, area, tagName)
            .then(result => expect(result.differences).to.equal(0));
    });

When test failed, it throws difference error code, for example:
![image](https://user-images.githubusercontent.com/3290297/30077535-fb1a6d26-9230-11e7-901e-63622c86fe6c.png)

**Comment by koola** [comment]
The result object should be `result.code`, see [docs](https://github.com/koola/pix-diff/blob/master/docs/index.md#checkscreentag-options--object) for details.
