### ISSUE TITLE
saveRegion throws error: element.getSize is not a function

### ISSUE THREAD

**Issue by qualityshepherd** [koola/pix-diff#6]
When attempting to `saveRegion`, I'm getting an error: `element.getSize is not a function`. I'm able to do a `saveScreen`. I'm running:

     browser.pixdiff.saveRegion($('div.page-viewport.top div.pinned-container'), tag);

I'm on Protractor 3.0, Node v4.2.1

**Comment by qualityshepherd** [comment]
The element was not being found... might want to add error handling for this condition.

**Comment by webdynamik** [comment]
+1
