### ISSUE TITLE
How do I re-baseline?

### ISSUE THREAD

**Issue by mfulton26** [koola/pix-diff#60]
I thought that setting `baseline: true` would create new images for the test cases that "fail" but it doesn't. Is there a flag for this? What I'd like to do is automatically overwrite the baseline files with the new images and then use git scm to review these differences (bitbucket and github both have decent image diff options in pull requests). That way I don't have to go find which ones failed and delete them and re-run the tests, etc.

**Comment by koola** [comment]
Please read the docs. `baseline: true` will only save images not found in `basepath`. If there is a previous image, then it's ignored.
