### ISSUE TITLE
Ignore region feature

### ISSUE THREAD

**Issue by mfulton26** [koola/pix-diff#61]
Would you be opposed to an `ignoreRegion` feature being added? I might be up to doing a pull request for that. e.g. I have a screen that I expect to be identical although I know that a certain `<output>` tag might contain a different value from time to time so I'd like to simply ignore the region for that element.

**Comment by koola** [comment]
PixDiff already supports blocking out regions using its underlying comparison engine [PixelDiff](https://github.com/koola/pixel-diff). 
```
[options.blockOut] | object \| Array.<object> | Object or list of objects with coordinates of blocked-out areas.
```

Here's an example of how to use it:
```javascript
browser.pixDiff = new PixDiff({
    basePath: 'path/to/baseline/',
    diffPath: 'path/to/diff/',
    width: 1366,
    height: 768
});

browser.pixDiff.checkScreen('examplePage', {blockOut: [{x:0, y:0, width:1366, height: 768}]});
```
