### ISSUE TITLE
ENOENT at Error (native)

### ISSUE THREAD

**Issue by mfulton26** [koola/pix-diff#62]
I get the following when using `checkPage` but not `checkScreen`:

```
Error: ENOENT: no such file or directory, open '...\baseline\general-Info-chrome-1333x888-dpr-1.png'
    at Error (native)

Failed: ENOENT: no such file or directory, open '...\baseline\general-Info-chrome-1333x888-dpr-1.png'
Error: ENOENT: no such file or directory, open '...\baseline\general-Info-chrome-1333x888-dpr-1.png'
    at Error (native)
From asynchronous test: 
```

The rest of the stack trace is just my Suite.describe and not any pix-diff or other dependency related code so I'm a bit confused as to where/why exactly the error is being thrown.

**Comment by koola** [comment]
Not sure, take a look at `desktop.spec.js` as that test is passing on my local.
