### ISSUE TITLE
Retina Screenshots

### ISSUE THREAD

**Issue by joaoffalcao** [koola/pix-diff#8]
I'm trying to use pix-diff but I'm facing two problems both related with retina displays. 

The first one, occurs when using saveRegion, on retina displays, the saved screenshot is not getting my region correctly, but just on retina.

The second problem, is that my retina page screenshots are different from my screenshots in regular displays for the same content, just because of the pixel ratio. 

Have you ever had this issues? If yes, how do you solved it?

Regards,
João Falcão

**Comment by koola** [comment]
Not had issues with retina images on my retina mbp or with running the tests. Images should ideally be like for like to minimize any of these inconsidtencues.

**Comment by joaoffalcao** [comment]
What browser are you using to run your tests? 
After some research I figured out that, on Chrome, there are retina issues, on PhantomJS don't.

**Comment by koola** [comment]
Am using Chrome Version 48.0.2564.116 (64-bit) on a MBP.

**Comment by joaoffalcao** [comment]
It's very strange, did you tried to run the same test in a regular display (a non retina one)?

**Comment by koola** [comment]
I've not had time to look into this. Could you provide any screens and/or errors thrown please?

**Comment by D4NH** [comment]
hmm I have a similar issue. 

on OSX: gets the correct coordinates. saves the image but on a different x/y coordinate because the image is an retina image.
on W7: gets the correct coordinates, saves the correct image

**Comment by joaoffalcao** [comment]
@D4NH to solve it, I start using PhantomJS instead of Chrome

**Comment by D4NH** [comment]
hmm.. what if we resize the image first before we crop it, would that work?

**Comment by joaoffalcao** [comment]
Yes, that was my first approach and that worked well, but I used `browser.executeScript()`, so the solution wasn't good enough.

**Comment by D4NH** [comment]
found a solution by getting the browser device pixel ratio and multiply all values within this part

`rect = { height: size.height, width: size.width, x: Math.floor(point.x), y: Math.floor(point.y) };`

**Comment by koola** [comment]
@D4NH That's interesting, any PR?

**Comment by D4NH** [comment]
getting errors when pushing, company restrictions :/ 

does this help? could be improved I think.
https://p.teknik.io/hctoY

**Comment by koola** [comment]
Thanks for the sample code. Please have a test using commit e8793e1cf52dd57875507fcc0006e33019391a72

**Comment by joaoffalcao** [comment]
@koola and @D4NH any news? I'm still with the same issue.

**Comment by koola** [comment]
@joaoffalcao Please have a try using the master as the fix is in.

**Comment by hkong** [comment]
I think I'm having this problem as well.  Chrome 52.  MacBookPro El Capitan.

When I do a saveScreen(), I get a PNG that is about 4 times larger than Chrome presents in the browser.  I can deal with that.  But when I do a saveRegion( element(by.css(...) ), I get the wrong region.

**Comment by koola** [comment]
Closing as all retina testing has reviled no issues.
