### ISSUE TITLE
Choose screenshot's file name

### ISSUE THREAD

**Issue by joaoffalcao** [koola/pix-diff#9]
Hi, 

What do you think of define the output name of the screenshot? Right now on ```saveRegion(element(by.css('.header'), 'module-header');```but the output file is named `module-header-chrome-480x320.png`. I want to name my file 'module-header' like I specified on the saveRegion(). 
What do you think of it?

Regards,
João Falcão

**Comment by koola** [comment]
That's quite easy to do, I'll add it for next release.

**Comment by joaoffalcao** [comment]
Do you have plans to bump the new version soon?

**Comment by koola** [comment]
Check out the latest release v1.0.8 ```formatImageName``` option for this.
